/**
 * FSRS optimizer tests (T080).
 *
 * Deterministic: every history is generated by a SEEDED PRNG (no `Math.random`),
 * fuzz is irrelevant (the optimizer never schedules), and the search is fixed-order.
 * We assert the HONEST contract:
 *  - `scoreParameters` returns finite `logLoss`/`rmse` and a LOWER score for a `w`
 *    that fits a synthetic history than for an obviously-wrong one;
 *  - `suggestParameters` NEVER returns params worse than the baseline;
 *  - below the data floor `sufficientData` is `false` and the suggestion == current;
 *  - every returned vector passes `checkParameters` (clamped + valid).
 */

import type { IsoTimestamp, ReviewRating } from "@interleave/core";
import { checkParameters, default_w } from "ts-fsrs";
import { describe, expect, it } from "vitest";
import {
  defaultParams,
  FSRS_PARAM_COUNT,
  hasSufficientData,
  type OptimizerHistory,
  optimizationSuggestionFromParts,
  sanitizeParams,
  scoreParameters,
  suggestParameters,
} from "./fsrs-optimizer";

/** A tiny deterministic PRNG (mulberry32) so histories are reproducible. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Generate a synthetic review history of WELL-RETAINED cards reviewed at sensible
 * spacing (intervals ≈ stability, so recall is usually high and grows with each
 * success). This matches the regime the FSRS `default_w` decay is tuned for, so the
 * default vector fits it BETTER than a degenerate over-decaying / tiny-stability
 * vector that predicts near-zero recall everywhere.
 */
function syntheticHistory(cards: number, reviewsPerCard: number, seed: number): OptimizerHistory[] {
  const rng = mulberry32(seed);
  const out: OptimizerHistory[] = [];
  const ratings: ReviewRating[] = ["good", "easy", "hard"];
  for (let c = 0; c < cards; c += 1) {
    const reviews: { rating: ReviewRating; reviewedAt: IsoTimestamp; elapsedDays: number }[] = [];
    let day = 0;
    let stability = 3;
    for (let r = 0; r < reviewsPerCard; r += 1) {
      // Review at ~70% of stability so recall stays high (well-spaced study).
      const elapsed = r === 0 ? 0 : Math.max(1, Math.round(stability * 0.7));
      day += elapsed;
      const recallProb = r === 0 ? 1 : Math.exp(-elapsed / Math.max(1, stability * 1.6));
      const recalled = rng() < recallProb;
      const rating: ReviewRating = recalled
        ? (ratings[Math.floor(rng() * ratings.length)] ?? "good")
        : "again";
      reviews.push({
        rating,
        reviewedAt: new Date(Date.UTC(2025, 0, 1) + day * 86_400_000).toISOString() as IsoTimestamp,
        elapsedDays: elapsed,
      });
      stability = recalled ? stability * 2 : Math.max(1, stability * 0.5);
    }
    out.push({ cardId: `card-${c}`, reviews });
  }
  return out;
}

describe("sanitizeParams", () => {
  it("accepts the default_w vector and returns a valid 21-number array", () => {
    const sane = sanitizeParams([...default_w]);
    expect(sane).not.toBeNull();
    expect(sane).toHaveLength(FSRS_PARAM_COUNT);
    expect(() => checkParameters(sane as number[])).not.toThrow();
  });

  it("rejects a wrong-length vector", () => {
    expect(sanitizeParams([0.1, 0.2, 0.3])).toBeNull();
  });

  it("rejects a vector with a non-finite value", () => {
    const bad = [...default_w];
    bad[5] = Number.NaN;
    expect(sanitizeParams(bad)).toBeNull();
  });

  it("clamps an out-of-range vector into the FSRS-safe range (never null for finite input)", () => {
    const huge = [...default_w].map(() => 1e9);
    const sane = sanitizeParams(huge);
    expect(sane).not.toBeNull();
    expect(() => checkParameters(sane as number[])).not.toThrow();
  });
});

describe("scoreParameters", () => {
  it("returns finite logLoss + rmse for a non-trivial history", () => {
    const history = syntheticHistory(30, 6, 1);
    const score = scoreParameters(history, defaultParams());
    expect(Number.isFinite(score.logLoss)).toBe(true);
    expect(Number.isFinite(score.rmse)).toBe(true);
    expect(score.reviewsScored).toBeGreaterThan(0);
  });

  it("scores a fitting w better (lower logLoss) than an obviously-wrong one", () => {
    const history = syntheticHistory(40, 6, 7);
    const good = scoreParameters(history, defaultParams());
    // An obviously-wrong vector: tiny initial stabilities + extreme decay so the
    // predicted recall is wildly miscalibrated.
    const wrong = [...default_w];
    wrong[0] = 0.05;
    wrong[1] = 0.05;
    wrong[2] = 0.05;
    wrong[3] = 0.05;
    wrong[20] = 0.9;
    const bad = scoreParameters(history, wrong);
    expect(good.logLoss).toBeLessThan(bad.logLoss);
  });

  it("returns +Infinity for a malformed parameter vector (never throws)", () => {
    const history = syntheticHistory(10, 4, 2);
    const score = scoreParameters(history, [1, 2, 3]);
    expect(score.logLoss).toBe(Number.POSITIVE_INFINITY);
    expect(score.reviewsScored).toBe(0);
  });

  it("is deterministic for a fixed history + params", () => {
    const history = syntheticHistory(25, 5, 3);
    const a = scoreParameters(history, defaultParams());
    const b = scoreParameters(history, defaultParams());
    expect(a).toEqual(b);
  });
});

describe("hasSufficientData", () => {
  it("is false for a thin history and true for a rich one (with a low test floor)", () => {
    const thin = syntheticHistory(3, 2, 5);
    const rich = syntheticHistory(25, 5, 5);
    expect(hasSufficientData(thin, { minReviews: 50, minCards: 10 })).toBe(false);
    expect(hasSufficientData(rich, { minReviews: 50, minCards: 10 })).toBe(true);
  });
});

describe("suggestParameters", () => {
  it("suggests nothing below the data floor (sufficientData false, suggestion == current)", () => {
    const thin = syntheticHistory(3, 2, 9);
    const suggestion = suggestParameters(thin, { minReviews: 1000, minCards: 100 });
    expect(suggestion.sufficientData).toBe(false);
    expect(suggestion.improvement).toBe(0);
    // The suggested params equal the current/default vector.
    expect(suggestion.params.w).toEqual([...default_w]);
  });

  it("never returns params scoring worse than the baseline (keeps baseline if nothing beats it)", () => {
    const history = syntheticHistory(40, 6, 11);
    const suggestion = suggestParameters(history, { minReviews: 50, minCards: 10 });
    expect(suggestion.suggested.logLoss).toBeLessThanOrEqual(suggestion.baseline.logLoss);
    expect(suggestion.improvement).toBeGreaterThanOrEqual(0);
  });

  it("always returns a checkParameters-valid, length-21 vector", () => {
    const history = syntheticHistory(40, 6, 13);
    const suggestion = suggestParameters(history, { minReviews: 50, minCards: 10 });
    expect(suggestion.params.w).toHaveLength(FSRS_PARAM_COUNT);
    expect(() => checkParameters([...suggestion.params.w])).not.toThrow();
    expect(suggestion.method).toBe("history-calibration");
  });

  it("is deterministic (same history → same suggestion)", () => {
    const history = syntheticHistory(40, 6, 17);
    const a = suggestParameters(history, { minReviews: 50, minCards: 10 });
    const b = suggestParameters(history, { minReviews: 50, minCards: 10 });
    expect(a.params.w).toEqual(b.params.w);
    expect(a.suggested).toEqual(b.suggested);
  });
});

describe("optimizationSuggestionFromParts (off-main runner result → typed suggestion)", () => {
  const SCORE = { logLoss: 0.4, rmse: 0.15, reviewsScored: 120 };

  it("re-wraps the worker's w vector into a checkParameters-valid FSRSParameters", () => {
    const w = Array.from({ length: FSRS_PARAM_COUNT }, (_, i) => 0.4 + i * 0.05);
    const suggestion = optimizationSuggestionFromParts({
      params: w,
      baseline: SCORE,
      suggested: { ...SCORE, logLoss: 0.3 },
      improvement: 0.1,
      reviewsScored: 120,
      method: "history-calibration",
      sufficientData: true,
    });
    expect(suggestion.params.w).toHaveLength(FSRS_PARAM_COUNT);
    expect(() => checkParameters([...suggestion.params.w])).not.toThrow();
    expect(suggestion.baseline).toEqual(SCORE);
    expect(suggestion.improvement).toBe(0.1);
    expect(suggestion.sufficientData).toBe(true);
  });

  it("degrades a malformed worker w vector to the default (never invalid params)", () => {
    const suggestion = optimizationSuggestionFromParts({
      params: [1, 2, 3], // wrong length
      baseline: SCORE,
      suggested: SCORE,
      improvement: 0,
      reviewsScored: 120,
      method: "history-calibration",
      sufficientData: false,
    });
    expect(suggestion.params.w).toEqual([...default_w]);
    expect(() => checkParameters([...suggestion.params.w])).not.toThrow();
  });
});
